dateModified: 1718403217
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - link
        - 'field:7f94ca16-453f-4ff9-84b4-1154a8a813d2' # Event Image
      type: native
    -
      key: singles
      type: native
    -
      heading: Channels
      type: heading
    -
      key: 'section:71b7a124-0908-470a-90c9-ddb43c64eabd' # Events
      type: native
email:
  fromEmail: ubcaccs@gmail.com
  fromName: ubcaccs.ca
  transportType: craft\mail\transportadapters\Sendmail
fs:
  awsBucket:
    hasUrls: true
    name: 'AWS bucket'
    settings:
      addSubfolderToRootUrl: false
      autoFocalPoint: false
      bucket: $S3_BUCKET
      bucketSelectionMode: manual
      cfDistributionId: $CLOUDFRONT_DISTRIBUTION_ID
      cfPrefix: $CLOUDFRONT_PATH_PREFIX
      expires: '3 months'
      keyId: $S3_KEY_ID
      makeUploadsPublic: false
      region: $S3_REGION
      secret: $S3_SECRET
      storageClass: ''
      subfolder: events
    type: craft\awss3\Fs
    url: $CLOUDFRONT_URL
  events:
    hasUrls: true
    name: Events
    settings:
      path: '@webroot/images/uploads/events'
    type: craft\fs\Local
    url: '@web/images/uploads/events'
  favicon:
    hasUrls: true
    name: Favicon
    settings:
      path: '@webroot/images/uploads'
    type: craft\fs\Local
    url: '@web/images/uploads'
meta:
  __names__:
    0d40cb9c-a6c7-40fd-a46a-37fbb4c2f761: Favicon # Favicon
    5e93ae0f-d6a1-4d7f-88d7-37a8f2c68196: ubcaccs.ca # ubcaccs.ca
    5edf3f64-12fc-4fd8-aa67-1f3ea36616e8: Description # Description
    06c4324d-71fe-476a-9b1f-3e6feaecf1ac: 'Public Schema' # Public Schema
    7f94ca16-453f-4ff9-84b4-1154a8a813d2: 'Event Image' # Event Image
    025f765b-22cc-4651-a46e-0da4cba5388d: ubcaccs.ca # ubcaccs.ca
    53e8b5f5-cedf-4544-b9ca-38f645b7dd6c: 'Survey URL' # Survey URL
    59ef1311-cc39-4344-a00d-5fa511f77a36: '350x350 Event' # 350x350 Event
    71b7a124-0908-470a-90c9-ddb43c64eabd: Events # Events
    087e0c6f-1168-48dd-b338-2bc4bdf4e93d: Events # Events
    665b2695-e5b3-4d3a-8c99-b36496609886: 'Frontend Schema' # Frontend Schema
    765c4e88-d809-4d54-80cc-57e653985857: About # About
    4501e90a-915d-4cd9-8d90-831f7592197a: Subtext # Subtext
    aac04264-1752-4643-a708-e6c6020d1aa2: 'End Time' # End Time
    b0c3c04f-de21-404d-a938-2def1f727a13: 'Begin Time ' # Begin Time 
    b9e65696-21d4-4990-a67a-05cd8555b297: Events # Events
    c27a1bb2-5418-435d-935b-a87899fb1de0: 'RSVP Required' # RSVP Required
    cc729cab-7cdb-489c-ab4f-7a0b60e804e3: About # About
    d759efbd-e6b8-46d7-b600-312486821a48: Common # Common
    d57181d9-bf62-4cd2-8922-f3f3ae7ee70f: Home # Home
    db94afb7-2344-4381-a3df-07d2072312a7: Events # Events
    dc2b295c-ecf2-4958-9687-2370da50ffa2: 'RSVP Link' # RSVP Link
    ebb6874b-10e3-4867-95cc-b3c079c408e2: Date # Date
    f74056b2-a18d-487f-a906-bba51c8ff7ec: Home # Home
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '2.0'
system:
  edition: solo
  live: true
  name: ubcaccs.ca
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
